### ISSUE TITLE
Organize the PDF of the Milestone Report

### ISSUE THREAD

**Issue by zcanfes** [bounswe/2021SpringGroup9#107]
I will export the Milestone report to PDF. Some pictures and heading are seen unorganized when this happens. So:
- [x] I will organize the images and headings. 
- [x] I will look for themes to use in the PDF file. 
- [x] I will use a software called: Typora and choose a theme. 
- [x] I will update the document when changes happen. 
- [x] I will reduce the size of the PDF since it becomes too large with images. 
- [x] I will convert it to PDF and send it to the group so that Melih Aydogdu can submit it to Moodle.

**Comment by zcanfes** [comment]
I have completed the tasks and send the final version of the document to the group. 
I have created 2 pdf files: one is for moodle (less in size  & image quality), other one is for uploading to GitHub which has the better image quality.
