### ISSUE TITLE
Write the Individual Deliverable for Milestone 2

### ISSUE THREAD

**Issue by zcanfes** [bounswe/2021SpringGroup9#180]
- [x] Add code, documentation, tests to support your deliverables
- [x] Add link to those from your repository
- [x] Executive Summary
- [x] Explain your API
- [x] Explain the reviews you have made
- [x] Describe each PR you created
- [x] Explain the issues you created and you were assigned
- [x] Identify the API Documentation for QuotesAPI
- [x] Other work you have done (research, finding bugs, meetings etc.)
- [x] Submit to Moodle

**Comment by zcanfes** [comment]
I have written the individual report.
