### ISSUE TITLE
Implement an API for getting all posts from the DB

### ISSUE THREAD

**Issue by zcanfes** [bounswe/2021SpringGroup9#260]
### Task: 
Implement an API for getting all posts from the database. 

### Type of task (new feature, writing tests, refactoring):
New feature

### Standards and rules to follow:
- [x] Create a class for this feature
- [x] Open a new branch from backend-master
- [x] Commit all changes
- [x] Open a PR to merge to backend-master
- [ ] Add Tests for this API

### Expected result:
A new url that gets all the posts from the database. This will be used at the homepage. 

### Additional notes:

**Deadline: 08.11.2021**

**Comment by zcanfes** [comment]
I have opened the Pull Request after solving the bugs mentioned in: 
* https://github.com/bounswe/2021SpringGroup9/issues/279
* https://github.com/bounswe/2021SpringGroup9/issues/278

**Comment by zcanfes** [comment]
I have completed the tasks. The code is now merged to master.
