### ISSUE TITLE
Implement an API for creating a post

### ISSUE THREAD

**Issue by mertlkn** [bounswe/2021SpringGroup9#261]
### Task:

Implement the post creation API.

### Type of task (new feature, writing tests, refactoring):

New feature.

### Standards and rules to follow:

- [x]  Create and implement the view.
- [x] Get Google API key for determining location.
- [x] Commit, push, create a pull request.
- [ ] Add tests.

### Expected result:

App will be able to get a post request and save it to database.

### Additional notes:

Related pull request can be found [here.](https://github.com/bounswe/2021SpringGroup9/pull/259)

**Deadline: xx.xx.xxxx**

08.11.2021

**Comment by mertlkn** [comment]
Other than tests, are implemented. Pull request is opened, got accepted and now merged. PR can be found [here.](https://github.com/bounswe/2021SpringGroup9/pull/259)

**Comment by mertlkn** [comment]
Tests are still a task.

**Comment by mertlkn** [comment]
Completed tasks. Can be closed. PRs can be found [here](https://github.com/bounswe/2021SpringGroup9/pull/259) and [here](https://github.com/bounswe/2021SpringGroup9/pull/264.)
