### ISSUE TITLE
Implement Post model to have Location and Tag lists

### ISSUE THREAD

**Issue by mertlkn** [bounswe/2021SpringGroup9#265]
### Task:

Improve the Post model such that it will have a list for locations and list for tags. Also implement the models for locations and tags.

### Type of task (new feature, writing tests, refactoring):

New feature

### Standards and rules to follow:

- [x] Implement location model.
- [x] Implement tag model.
- [x] Implement the fields (locations and tags) in Post model.

### Expected result:

Our database is updated such that there are locations and tags collections. And their ids will also be stored in related posts.

### Additional notes:

Related pull request can be found [here.](https://github.com/bounswe/2021SpringGroup9/pull/264)

**Deadline: 09.11.2021**

**Comment by mertlkn** [comment]
They are implemented in [backend_model_location_tag](https://github.com/bounswe/2021SpringGroup9/tree/backend_model_location_tag) branch.
