### ISSUE TITLE
Revise the create post API in backend to have list of locations and tags

### ISSUE THREAD

**Issue by mertlkn** [bounswe/2021SpringGroup9#266]
### Task:

Post model now includes locations and tags lists. To make endpoint functional again, method should be revised and corrected.

### Type of task (new feature, writing tests, refactoring):

Refactoring

### Standards and rules to follow:

- [x] Implement getting locations from request and creating location objects.
- [x] Saving locations' id's to related posts.
- [x] Implement getting tags from request and creating tag objects.
- [x] Saving tags' id's to related posts.

### Expected result:

Now API is functional again with the following request body:

{
    "title":"denemeTitle7",
    "story":"denemeStory7",
    "owner":"denemeOwner7",
    "locations":["Istanbul","Rome","Milan"],
    "storyDate":"2021-11-06 17:21:20.108574",
    "tags": ["cmpe","boun","güney","kuzey"]
}

### Additional notes:

Related pull request can be found [here.](https://github.com/bounswe/2021SpringGroup9/pull/264)

**Deadline: 09.11.2021**
