### ISSUE TITLE
Creating pop-ups for the unimplemented features

### ISSUE THREAD

**Issue by ahmetsenturk** [bounswe/2021SpringGroup9#280]
### Task:
Some of the features that we have added on the frontend do not have their functionalities at the moment (e.g., the search bar at the top of the home page). So, I will add a pop-up mechanism that will be shown to the user when these buttons are pressed.

### Type of task (new feature, writing tests, refactoring):
New feature

### Standards and rules to follow:
- [x] Pop-up for the buttons under the post (i.e., comment, share, save, and report buttons)
- [x] Pop-up for the search button
- [x] Pop-up for the buttons on the top bar (i.e., discovery and menu buttons)

### Expected result:
When a feature that doesn't have functionality in the background is pressed/clicked, a pop-up should be shown to the user to let the user know that it is not working at the moment.

### Additional notes:

**Deadline: 11.11.2021**

**Comment by ahmetsenturk** [comment]
I have started implementing this feature. As a guideline, I  will follow this [source](https://mui.com/components/snackbars/) as @mecolak suggested.

**Comment by ahmetsenturk** [comment]
I have completed the task and it can be seen on this [branch](https://github.com/bounswe/2021SpringGroup9/tree/frontend-popup_unimplemented_feats)
