### ISSUE TITLE
Implement Get, Put and Delete API Functionalities

### ISSUE THREAD

**Issue by melihaydogd** [bounswe/2021SpringGroup9#282]
### Task:

Implement the post get, put and delete API. 

### Type of task (new feature, writing tests, refactoring):

New feature.

### Standards and rules to follow:

- [x] Create and implement the view.
- [x] Create a pull request.
- [ ] Merge the pull request into [backend-master](https://github.com/bounswe/2021SpringGroup9/tree/backend-master) branch.
- [ ] Implement tests.

### Expected result:

The application can return a specific post, update a specific post and delete a specific post. 

### Additional notes:

The pull request is here [here.](https://github.com/bounswe/2021SpringGroup9/pull/275)

**Deadline: 11.11.2021**
