### ISSUE TITLE
Create Workflow for Backend Deployment

### ISSUE THREAD

**Issue by melihaydogd** [bounswe/2021SpringGroup9#283]
### Task:

Workflow will be created to deploy the backend to AWS EC2 instance.

### Type of task (new feature, writing tests, refactoring):

New feature.

### Standards and rules to follow:

- [x] Create the workflow for two different environments.
- [x] Create a pull request.
- [x] Merge the pull request into [backend-master](https://github.com/bounswe/2021SpringGroup9/tree/backend-master) branch.

### Expected result:

The application starts running on AWS EC2 instance.

### Additional notes:

The pull request can be found [here](https://github.com/bounswe/2021SpringGroup9/pull/274).

**Deadline: 11.11.2021**

**Comment by melihaydogd** [comment]
Workflow created and merged to the backend-master. PR can be found [here](https://github.com/bounswe/2021SpringGroup9/pull/274).
