### ISSUE TITLE
Implement Unit Tests

### ISSUE THREAD

**Issue by zcanfes** [bounswe/2021SpringGroup9#538]
### Task:
Implement unit tests for the functionalities you added: 
- [x] Following other users
- [x] Following self
- [x] Unfollowing
- [x] Sending follow request to private accounts
- [x] Accept follow request
- [x] Decline follow request
- [x] Change account to private/public
- [x] Report user
- [x] Report story

### Type of task (new feature, writing tests, refactoring):

Writing tests

### Standards and rules to follow:

Follow the rules of writing unit tests. 

### Expected result:

All tests should pass and return OK. 

### Additional notes:

**Deadline: 04.01.2022**

**Comment by zcanfes** [comment]
I have written all the unit tests and noticed a bug during implementation. Finding a bug helped me understand the importance of unit tests :) The related pull request can be found [here](https://github.com/bounswe/2021SpringGroup9/pull/541).
